services:
  web_server:
    container_name: server

    volumes:
      - ./server/html:/var/www/html

    build:
      context: ./server
      dockerfile: Dockerfile

    restart: always

    ports:
      - 8000:80
